services:
  tablo-homerun-proxy:
    build: .
    container_name: tablo-homerun-proxy
    network_mode: host
    environment:
      NAME: "Tablo 4th Gen Proxy"
      DEVICE_ID: "12345679"
      PORT: "8181"
      LINEUP_UPDATE_INTERVAL: "30"
      CREATE_XML: "false"
      GUIDE_DAYS: "2"
      INCLUDE_PSEUDOTV_GUIDE: "false"
      LOG_LEVEL: "info"
      GUIDE_UPDATE_INTERVAL: "24"
      INCLUDE_OTT: "true"
      ADMIN_PASSWORD: "<admin password>"
    volumes:
      - ./data:/data
    restart: unless-stopped
